[versions]
aboutLibraries = "13.1.0"
buildKonfig = "0.17.1"
agp = "9.0.0-beta05"
androidCompileSdk = "36"
androidMinSdk = "24"
androidTargetSdk = "36"
androidxActivity = "1.12.0"
androidxDataStore = "1.1.7"
# rememberSaveable状態保持バグ修正版 (https://github.com/slackhq/circuit/discussions/2455)
circuit = "0.32.0-alpha02-composejb-1.10.0-rc02"
circuitSharedElements = "0.31.0"
coil = "3.3.0"
colorPickerCompose = "1.1.3"
ktor = "3.3.3"
composeMultiplatform = "1.10.0-rc02"
kotlin = "2.3.0-RC3"
ksp = "2.3.2"
material3 = "1.9.0"
materialKolor = "4.0.0"
metro = "0.8.2"

[libraries]
# build-logic dependencies
androidGradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidKmpLibraryGradle = { module = "com.android.kotlin.multiplatform.library:com.android.kotlin.multiplatform.library.gradle.plugin", version.ref = "agp" }
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
composeCompilerGradle = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
composeGradle = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composeMultiplatform" }
kspGradle = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }
metroGradle = { module = "dev.zacsweers.metro:dev.zacsweers.metro.gradle.plugin", version.ref = "metro" }
buildKonfigGradle = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "buildKonfig" }
# FieldSpec.Type.STRINGのimportに必要 (https://github.com/yshrsmz/BuildKonfig/issues/227)
buildKonfigCompiler = { module = "com.codingfeline.buildkonfig:buildkonfig-compiler", version.ref = "buildKonfig" }

# app dependencies
aboutLibrariesCore = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }
aboutLibrariesComposeM3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
androidxDataStorePreferences = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidxDataStore" }
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
circuitCodegen = { module = "com.slack.circuit:circuit-codegen", version.ref = "circuit" }
coilCompose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coilNetworkKtor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
colorPickerCompose = { module = "com.github.skydoves:colorpicker-compose", version.ref = "colorPickerCompose" }
ktorClientOkhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktorClientDarwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
circuitCodegenAnnotations = { module = "com.slack.circuit:circuit-codegen-annotations", version.ref = "circuit" }
circuitFoundation = { module = "com.slack.circuit:circuit-foundation", version.ref = "circuit" }
circuitSharedElements = { module = "com.slack.circuit:circuit-sharedelements", version.ref = "circuitSharedElements" }
composeComponentsResources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
composeFoundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
composeMaterial3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
composeRuntime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
composeUi = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
composeUiTooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
composeUiToolingPreview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }

[plugins]
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }

# Convention Plugins
circuitSampleKmpLibrary = { id = "kmp.library" }
circuitSampleKmpLibraryCompose = { id = "kmp.library.compose" }
circuitSampleKmpFeature = { id = "kmp.feature" }
circuitSampleBuildKonfig = { id = "buildkonfig" }